version: '3.9'

services:
  api:
    image: high-school-quest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=HighSchoolQuestDb;User=sa;Password=HighSchoolQuestDb123@"
    
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: HighSchoolQuestDb123@
      ACCEPT_EULA: Y
    ports:
      - "1439:1433"
