version: '3.9'

services:
  api:
    image: high-school-quest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      #- "5001:443"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: "Development" # Corrected the environment variable here
      ASPNETCORE_URLS: "http://+:80"
    networks:
      - my_network  
      #ASPNETCORE_Kestrel__Certificates__Default__Password: "password"
      #ASPNETCORE_Kestrel__Certificates__Default__Path : "/https/aspnetapp.pfx"

  # db:
  #   image: mcr.microsoft.com/mssql/server
  #   environment:
  #     SA_PASSWORD: "HighSchoolQuestDb123@" # Enclose the password in quotes
  #     ACCEPT_EULA: "Y" # Enclose the value in quotes
  #   ports:
  #     - "1435:1433" # Corrected the port mapping


  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - my_network  

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: my@email.com
      PGADMIN_DEFAULT_PASSWORD: my_password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - my_network  

volumes:
  pg_data:

networks:
  my_network:
    driver: bridge  
